image: luthersystems/build-go:v0.0.59

pipelines:
  pull-requests:
    '**':
      - step:
          script:
            - apt-get update && apt-get install -y libltdl-dev zip
            - source bitbucket-pipelines-go.sh
            - cd ${IMPORT_PATH} && make print-go-env static-checks go-test
