name: CI Tests

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: luthersystems/build-go:v0.0.88
    steps:
      - uses: actions/checkout@v4
      - name: Run CI tests
        run: make citest
